# Generated by Django 3.2.4 on 2021-06-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
